freebsd_instance:
  image_family: freebsd-15-0

task:
  name: Build SonicDE Ports (GhostBSD Unstable Repo)
  timeout_in: 60m

  setup_ghostbsd_repo_script:
    - echo ">>> Disabling FreeBSD pkg repos"
    - mkdir -p /usr/local/etc/pkg/repos
    - echo "FreeBSD: { enabled: no }" > /usr/local/etc/pkg/repos/FreeBSD.conf

    - echo ">>> Enabling GhostBSD Unstable repo"
    - cat <<EOF > /usr/local/etc/pkg/repos/GhostBSD.conf
GhostBSD: {
  url: "pkg+http://pkg.ghostbsd.org/unstable/amd64",
  mirror_type: "srv",
  enabled: yes,
  priority: 100
}
EOF

    - echo ">>> Bootstrapping pkg from GhostBSD"
    - env ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg update -f

  install_deps_script:
    - echo ">>> Installing KDE6/Qt6 build deps from GhostBSD repo"
    - pkg install -y git pkgconf cmake ninja llvm17 \
        qt6-base qt6-tools qt6-declarative qt6-quickcontrols2 \
        kde6-frameworks kde6-plasma kde6-gear \
        wayland wayland-protocols xorg-minimal

  build_script:
    - echo ">>> Detecting changed ports"
    - PORTS=$(git diff --name-only HEAD~1 | grep '/' | cut -d/ -f1-2 | sort -u)
    - if [ -z "$PORTS" ]; then echo "No ports changed"; exit 0; fi

    - for p in $PORTS; do
        echo ">>> Building port: $p";
        cd $p;
        make makesum;
        make clean;
        make stage;
        make check-plist;
        make package;
        cd -;
      done

  artifacts:
    path: "**/*.pkg"
    type: file
